# Generated by Django 3.2.3 on 2022-02-12 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(default='', max_length=300)),
                ('attendance_count', models.IntegerField(default=1)),
                ('description', models.CharField(default='', max_length=500)),
                ('cost', models.IntegerField(blank=True, default=0)),
                ('capacity', models.IntegerField(blank=True, default=0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
